#!bin/bash

CHOICE=$(echo -e "es\nus\ndvorak" | dmenu -p layout)

case "$CHOICE" in
	es) setxkbmap es -option caps:escape & ;;
	us) setxkbmap us -option caps:escape & ;;
	dvorak) setxkbmap es -option caps:escape & ;;
esac
