#!/bin/bash
CHOICE=$(echo -e "laptop\nexternal\ndual\narandr" | dmenu -p monitor)

case "$CHOICE" in
	laptop) xrandr --output eDP --primary --mode 1920x1080 --output HDMI-2 --off & ;;
	external) xrandr --output HDMI-2 --primary --mode 1920x1080 --output eDP-1 --off & ;;
	dual) xrandr --output HDMI-2 --primary --mode 1920x1080 --output eDP-1 --mode 1680x1050 --left-of HDMI-2 & ;;
	arandr) arandr & disown;;
esac
